#!/usr/bin/env bash

# export DOTNET_ROOT=/opt/dotnet
export EDITOR=vim
export HISTSIZE=32768
export HISTFILESIZE="${HISTSIZE}"
export HISTCONTROL=ignoreboth
export IDF_PATH=~/Repos/esp
export IDF_TOOLS_PATH=~/.espressif
export NODE_REPL_HISTORY=~/.node_history
# export TERMINAL=termite
# export XDG_CURRENT_DESKTOP=Unity
export XKB_DEFAULT_LAYOUT=us
export XKB_DEFAULT_VARIANT=altgr-intl
export XKB_DEFAULT_OPTIONS=compose:menu

if hash wslview 2> /dev/null; then
        export BROWSER=wslview
fi;
